import rtconfig
from building import *
import os

cwd  = GetCurrentDir()

src  = Glob('*.c')
src  += Glob('lvgl/*.c')

path = [cwd]
path += [cwd + '/lvgl']


group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
